// Load your images on page-load
function preloader() {
  const imagesList = ["./img/img-1.jpg", "./img/img-2.jpg", "./img/img-3.jpg"];
  const images = [];
  for (let i = 0; i < imagesList.length; i++) {
    images[i] = new Image();
    images[i].src = imagesList[i];
  }

  // Images ready to be used:
  console.log(
    `Preloaded images:\n\t${images[0].src}\n\t${images[1].src}\n\t${images[2].src}`
  );
}
window.addEventListener("load", preloader);

//database

let database = {
  contentOne: {
    title: "Wind Energy",
    url: "img/wind-energy.jpg",
    alt: "An image of windmill in plateaus at sunset",
    body: "Wind energy is a renewable and sustainable source of power that harnesses the natural movement of air to generate electricity. It is produced using wind turbines, which convert the kinetic energy of the wind into mechanical power. This clean energy source reduces dependence on fossil fuels, lowers greenhouse gas emissions, and contributes to a greener environment. Wind farms, both onshore and offshore, are increasingly being developed worldwide as technology advances, making wind power more efficient and cost-effective. Despite challenges such as intermittency and land use concerns, wind energy remains one of the fastest-growing renewable energy sources, playing a crucial role in the transition toward a sustainable future.",
  },
  contentTwo: {
    title: "Thermal Energy",
    url: "img/thermal-energy.jpg",
    alt: "An image of a hot spring in a geothermal area",
    body: "Thermal energy refers to the internal energy of a substance due to the motion of its molecules. It is generated by the movement of particles within an object, with higher temperatures indicating greater molecular motion. Thermal energy can be harnessed from various sources, including the Sun, geothermal activity, and the burning of fossil fuels. It plays a crucial role in everyday life, powering heating systems, industrial processes, and electricity generation in thermal power plants. While conventional methods of producing thermal energy rely on non-renewable resources, sustainable alternatives like solar thermal and geothermal energy are gaining importance in reducing environmental impact and promoting clean energy solutions.",
  },
  contentThree: {
    title: "Solar Energy",
    url: "img/solar-energy.jpg",
    alt: "An image of plains with so many Solar Panels",
    body: "Solar energy is a renewable and abundant source of power derived from the Sun’s radiation. It is harnessed using technologies like solar panels, which convert sunlight into electricity through photovoltaic cells, and solar thermal systems, which capture heat for various applications. Solar energy is a clean and sustainable alternative to fossil fuels, reducing greenhouse gas emissions and dependency on non-renewable resources. It is widely used for residential, commercial, and industrial purposes, powering homes, businesses, and even large-scale solar farms. As technology advances and costs decrease, solar energy continues to grow as a key player in the transition toward a greener and more sustainable future.",
  },
};

// Get references to hard coded HTML

let content = document.querySelector(".content");
let btns = document.querySelectorAll(".controls button");

//Display the initial content
content.innerHTML = `<h2>${database.contentOne.title}</h2>
<img = src="${database.contentOne.url}" alt="${database.contentOne.alt}">
<p>${database.contentOne.body}</p>
`;

//Event handler defined
function handleClick(e) {
  for (let btn of btns) {
    if (btn.hasAttribute("id")) {
      btn.removeAttribute("id");
    }
  }

  let currentlyClicked = e.target;
  //console.log(currentlyClicked.dataset.id);
  let key = currentlyClicked.dataset.id;
  content.innerHTML = `<h2>${database[key].title}</h2>
 <img = src="${database[key].url}" alt="${database[key].alt}">
<p>${database[key].body}</p>`;
  currentlyClicked.id = "active-button";
}

for (let btn of btns) {
  btn.addEventListener("click", handleClick);
}
